name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build kaiheila-dotnet.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test kaiheila-dotnet.sln --no-restore --verbosity normal
      
  pack:
    name: Build Package
    
    needs: [build]
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build kaiheila-dotnet.sln --configuration Release --no-restore
    - name: Pack
      run: dotnet pack kaiheila-dotnet.sln -o src/bin/publish/ --configuration Release --no-restore
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kaiheila-dotnet-nupkg-${{ github.sha }}
        path: src/bin/publish
